version: '3.7'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: task
      DB_USERNAME: task
      DB_PASSWORD: task
      DB_SYNCHRONIZE: true
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
      POSTGRES_DB: task
  test_db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: task_test
      POSTGRES_PASSWORD: task_test
      POSTGRES_DB: task_test
