POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "abesalomi",
  "password": "abesalomi"
}


> {%
    client.global.set("token", response.body['access_token']);
%}


###
GET http://localhost:5000/api/auth/profile
Authorization: bearer {{token}}

> {%
    client.global.set("user_id", response.body['id']);
%}
