GET http://localhost:5000/api/users
Authorization: bearer {{token}}

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "username": "abesalomi",
  "firstName":  "Abesalomi",
  "lastName": "Gogatishvili",
  "password":  "abesalomi",
  "roles": ["SELLER"]
}

