POST http://localhost:5000/api/users/deposit
Content-Type: application/json
Authorization: bearer {{token}}

{
  "amount": 6
}

###
POST http://localhost:5000/api/users/deposit
Content-Type: application/json
Authorization: bearer {{token}}

{
  "amount": 100
}
