GET http://localhost:5000/api/users
Authorization: bearer {{token}}

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "username": "abesalomi",
  "password":  "abesalomi",
  "deposit": 0,
  "roles": ["SELLER"]
}

###
DELETE http://localhost:5000/api/users/{{user_id}}
Authorization: bearer {{token}}

###
DELETE http://localhost:5000/api/users/0
Authorization: bearer {{token}}


###
PATCH http://localhost:5000/api/users
Content-Type: application/json
Authorization: bearer {{token}}

{
  "password": "abesalomi1"
}
